In [ ]:
! pip install deeppavlov
! pip install transformers

In [ ]:
from deeppavlov import configs, train_model, build_model
from deeppavlov import evaluate_model
from deeppavlov.core.commands.utils import parse_config
from sklearn.model_selection import train_test_split
import json
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%%time
config = parse_config('/content/drive/MyDrive/ColabNotebooks/SkillBox/Configs/config_rubert_test.json')
model = train_model(config, download=False)
evaluate_model(config)

In [ ]:
%%time
config = parse_config('/content/drive/MyDrive/ColabNotebooks/SkillBox/Configs/config_rubert_test_10.json')
model_10 = train_model(config, download=False)
evaluate_model(config)

In [ ]:
%%time
config = parse_config('/content/drive/MyDrive/ColabNotebooks/SkillBox/Configs/config_rubert_test_100.json')
model_100 = train_model(config, download=False)
evaluate_model(config)

In [ ]:
%%time
config = parse_config('/content/drive/MyDrive/ColabNotebooks/SkillBox/Configs/config_rubert_test.json')
model = build_model(config, download=False)
evaluate_model(config)

In [ ]:
df = pd.DataFrame({'Prob': model(['Добрый день. У вас есть, рассрочка не от банка? Пример заплатил, месяц отучился)))'])[0][0], 'Class': list(model['classes_vocab'].keys())})

In [ ]:
import numpy as np

arr = np.array([1, 3, 2, 9, 7, 5])
top_3_indices = arr.argsort()[-3:][::-1]

# Get the values using advanced indexing
top_3_values = arr[top_3_indices]

print(top_3_indices)
print(top_3_values)

[3 4 5]
[9 7 5]


In [ ]:
test = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/test.csv')

def get_indexes(prob, top=3):
    sorted_indices = sorted(range(len(prob)), key=lambda k: prob[k], reverse=True)
    return sorted_indices[:top]

def get_top_intents(test, model, top=3):
    intents = list(model['classes_vocab'].keys())
    #df = pd.DataFrame(columns=['intent', 'top_1', 'top_2', 'top_3'])
    for index, row in test.iterrows():
        get_probs = model([row[0]])[0][0]
        selected = [intents[i] for i in get_indexes(get_probs)]
        probabilities = [get_probs[i] for i in get_indexes(get_probs)]
        print('fact: ', row[1], 'pred: ', dict(zip(selected, probabilities)))

In [ ]:
model(['Рассрочка'])[0][0]

array([7.00445089e-04, 1.11818545e-05, 1.79275652e-04, 4.07867738e-05,
       1.14241513e-04, 1.44173275e-03, 9.99926567e-01, 6.23239521e-06,
       3.58034549e-06, 1.95358116e-05, 5.90470677e-07, 2.58344604e-04,
       1.32539453e-05, 7.68812879e-06, 2.75393832e-04, 1.13659171e-05,
       1.60988691e-06, 3.62000836e-04, 1.40127149e-05, 5.93839195e-06,
       5.28046803e-05, 2.27558950e-04, 1.57949908e-04, 9.50345348e-05,
       1.55035705e-05, 2.14060754e-04, 2.86026034e-06, 1.91243562e-05,
       1.86296631e-04, 5.61639899e-04, 6.11701616e-05, 7.56127993e-04],
      dtype=float32)

In [ ]:
get_top_intents(test, model, top=3)

fact:  Ответ на недозвон pred:  {'Отказ': 0.49734202, 'Благодарность': 0.36049682, 'Ответ на недозвон': 0.03668638}
fact:  Саппорт pred:  {'Саппорт': 0.84599066, 'Вопрос по курсу': 0.29024076, 'Трудоустройство': 0.06975952}
fact:  Ответ на недозвон pred:  {'Ответ на недозвон': 0.9796213, 'Не перезвонил МОП': 0.072665684, 'Консультация': 0.039916385}
fact:  Отказ pred:  {'Отказ': 0.83766687, 'Благодарность': 0.1353807, 'Консультация': 0.023793153}
fact:  Реферальная программа pred:  {'Вопрос по курсу': 0.19067419, 'Саппорт': 0.14821425, 'Трудоустройство': 0.058721468}
fact:  Формат обучения pred:  {'Цена': 0.72054213, 'Вопрос по курсу': 0.32446104, 'Формат обучения': 0.022341533}
fact:  Формат обучения pred:  {'Вопрос по курсу': 0.7097164, 'Формат обучения': 0.1230054, 'Цена': 0.040921513}
fact:  Сертификат pred:  {'Трудоустройство': 0.86783385, 'Сертификат': 0.09268854, 'Вопрос по курсу': 0.0445231}
fact:  Саппорт pred:  {'Трудоустройство': 0.5572591, 'Саппорт': 0.29827338, 'Консультац

In [ ]:
import numpy as np

arr = np.array([1, 3, 2, 9, 7, 5])
top_3_indices = arr.argsort()[-3:][::-1]

# Get the values using advanced indexing
top_3_values = arr[top_3_indices]

print(top_3_indices)
print(top_3_values)

[3 4 5]
[9 7 5]


In [ ]:
get_top_intents(test, model, top=3)

In [ ]:
lst = [1, 3, 2, 9, 7, 5]
sorted_indices = sorted(range(len(lst)), key=lambda k: lst[k], reverse=True)
top_3_indices = sorted_indices[:3]

print(top_3_indices)

[3, 4, 5]


In [ ]:
for index, row in df.iterrows():

In [ ]:
#! python -m deeppavlov riseapi /content/drive/MyDrive/ColabNotebooks/SkillBox/Configs/config_rubert_test.json

In [ ]:
#model_10(['Добрый день. У вас есть, рассрочка не от банка? Пример заплатил, месяц отучился)))'])

In [ ]:
#model_100(['Добрый день. У вас есть, рассрочка не от банка? Пример заплатил, месяц отучился)))'])